LOGS:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: '%(asctime)-18s - %(name)-8s - %(levelname)-8s : %(message)s'
      datefmt: "%m-%d-%Y_%H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    logfile:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: webhook.log
      maxBytes: 10485760 #10mb
      backupCount: 5
      encoding: utf8
  root:
    level: DEBUG
    handlers: [logfile, console]